### ISSUE TITLE
Lean 4 version?

### ISSUE THREAD

**Issue by madvorak** [digama0/lean4lean#1]
Could you please indicate which version of Lean 4 is your project compatible with? I can see that you use `lean4:v4.7.0-rc2` but it does not mean that you compile everything that `lean4:v4.7.0-rc2` compiles, right?

**Comment by digama0** [comment]
This program compiles on v4.7.0-rc2. I don't know what you mean by "you compile everything that lean4:v4.7.0-rc2 compiles", this is not a lean compiler. But it is capable of checking olean files on this version. It's also not particularly tied to the lean version, so if you try bumping the version to match your project there is a good chance it will work.
